[package]
name = "foundry-soft-deletes"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sea-orm = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
