[package]
name = "rf-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["fs"] }
uuid.workspace = true
chrono.workspace = true
bytes = "1.5"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
